local dir       = require('gears').filesystem.get_configuration_dir()

_G.preferences  = {
	theme = 'dark',
	titlebar_style = 'windows',
	wallpaper      = dir ..'themes/wp.jpg',
	icon_user      = dir .. 'icon-user.png',
	dock           = true,
	dock_autohide  = true,
	dock_bg_solid  = false,
	dock_apps = {
		'thunar',
		'spacefm',
		'firefox',
		'lollypop',
		'audacious',
		'galculator',
		'evince.desk',
		'libreoffice-writer',
		'gvim',
		'terminator',
		'ranger',
		'smplayer',
		'synaptic',
		'gimp',
		'inkscape',
		'gpicview',
		'blender',
		'mupen64plus-qt'
	},

	topbar_tasklist        = false,
	topbar_bg_solid        = false,
	topbar_hide_maximized  = false,
	topbar_autohide        = false,

	desktop_icon           = false,
	client_rounded_corners = 8,
	switcher_preview       = false,
	web_browser     = 'firefox',
	music_player    = 'lollypop',
	launcher        = 'rofi -show drun',
	network_manager = 'wicd-gtk',
	sound_manager   = 'pavucontrol',
	package_manager = 'synaptic-pkexec',
	shell = '/bin/sh',
	command_vol_up = '',
	command_vol_down = '',
	command_play_player = '',
	command_pause_player = '',
}
